import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function TicketFilters({ onFilterChange, currentFilters }) {
    const handleChange = (field, value) => {
        onFilterChange({
            ...currentFilters,
            [field]: value
        });
    };
    return (_jsxs("div", { className: "filters-container", children: [_jsxs("div", { className: "filter-group", children: [_jsx("label", { htmlFor: "filter-status", children: "Status:" }), _jsxs("select", { id: "filter-status", value: currentFilters.status, onChange: (e) => handleChange('status', e.target.value), children: [_jsx("option", { value: "", children: "All Status" }), _jsx("option", { value: "Open", children: "Open" }), _jsx("option", { value: "In Progress", children: "In Progress" }), _jsx("option", { value: "Resolved", children: "Resolved" }), _jsx("option", { value: "Closed", children: "Closed" })] })] }), _jsxs("div", { className: "filter-group", children: [_jsx("label", { htmlFor: "filter-priority", children: "Priority:" }), _jsxs("select", { id: "filter-priority", value: currentFilters.priority, onChange: (e) => handleChange('priority', e.target.value), children: [_jsx("option", { value: "", children: "All Priorities" }), _jsx("option", { value: "Low", children: "Low" }), _jsx("option", { value: "Medium", children: "Medium" }), _jsx("option", { value: "High", children: "High" }), _jsx("option", { value: "Critical", children: "Critical" })] })] }), _jsxs("div", { className: "filter-group", children: [_jsx("label", { htmlFor: "filter-category", children: "Category:" }), _jsxs("select", { id: "filter-category", value: currentFilters.category, onChange: (e) => handleChange('category', e.target.value), children: [_jsx("option", { value: "", children: "All Categories" }), _jsx("option", { value: "IT", children: "IT" }), _jsx("option", { value: "HR", children: "HR" }), _jsx("option", { value: "Finance", children: "Finance" }), _jsx("option", { value: "Facilities", children: "Facilities" }), _jsx("option", { value: "General", children: "General" })] })] })] }));
}
